#!/usr/bin/env bash

ignoreINT() {
  printf "received SIGINT but i'm ignoring it!\n"
}

ignoreTERM() {
  printf "received SIGTERM but i'm ignoring it!\n"
}

trap ignoreINT INT
trap ignoreTERM TERM

while true; do
  printf "tick: %s -- FOO:%s\n" "$*" "${FOO:-}"
  sleep 1
done
